#pragma once

#define ICON_LC_ACTIVITY             "\xEE\x80\xB8"
#define ICON_LC_ALERT_TRIANGLE       "\xEE\x86\x93"
#define ICON_LC_CHECK                "\xEE\x81\xAC"
#define ICON_LC_CHEVRON_DOWN         "\xEE\x81\xAD"
#define ICON_LC_CHEVRON_LEFT         "\xEE\x81\xAE"
#define ICON_LC_CHEVRON_RIGHT        "\xEE\x81\xAF"
#define ICON_LC_CHEVRON_UP           "\xEE\x81\xB0"
#define ICON_LC_CLOCK                "\xEE\x82\x87"
#define ICON_LC_CLOUD                "\xEE\x82\x88"
#define ICON_LC_COPY                 "\xEE\x82\x9E"
#define ICON_LC_CPU                  "\xEE\x82\xA9"
#define ICON_LC_DATABASE             "\xEE\x82\xAD"
#define ICON_LC_DOWNLOAD             "\xEE\x82\xB2"
#define ICON_LC_EXTERNAL_LINK        "\xEE\x82\xB9"
#define ICON_LC_EYE                  "\xEE\x82\xBA"
#define ICON_LC_EYE_OFF              "\xEE\x82\xBB"
#define ICON_LC_FILE_TEXT            "\xEE\x83\x8C"
#define ICON_LC_FILTER               "\xEE\x83\x9C"
#define ICON_LC_FLAG                 "\xEE\x83\x91"
#define ICON_LC_FOLDER               "\xEE\x83\x97"
#define ICON_LC_GLOBE                "\xEE\x83\xA8"
#define ICON_LC_HASH                 "\xEE\x83\xAF"
#define ICON_LC_HEART                "\xEE\x83\xB2"
#define ICON_LC_INFO                 "\xEE\x83\xB9"
#define ICON_LC_KEY                  "\xEE\x83\xBD"
#define ICON_LC_LAYERS               "\xEE\x94\xA9"
#define ICON_LC_LAYOUT_GRID          "\xEE\x83\xBF"
#define ICON_LC_LINK                 "\xEE\x84\x82"
#define ICON_LC_LIST                 "\xEE\x84\x86"
#define ICON_LC_LOCK                 "\xEE\x84\x8B"
#define ICON_LC_LOG_OUT              "\xEE\x84\x8E"
#define ICON_LC_MAP_PIN              "\xEE\x84\x91"
#define ICON_LC_MESSAGE_CIRCLE       "\xEE\x84\x96"
#define ICON_LC_MINUS                "\xEE\x84\x9C"
#define ICON_LC_MONITOR              "\xEE\x84\x9D"
#define ICON_LC_PLAY                 "\xEE\x84\xBC"
#define ICON_LC_PLUS                 "\xEE\x84\xBD"
#define ICON_LC_POWER                "\xEE\x85\x80"
#define ICON_LC_REFRESH_CW           "\xEE\x85\x85"
#define ICON_LC_SAVE                 "\xEE\x85\x8D"
#define ICON_LC_SEARCH               "\xEE\x85\x91"
#define ICON_LC_SEND                 "\xEE\x85\x92"
#define ICON_LC_SERVER               "\xEE\x85\x93"
#define ICON_LC_SETTINGS             "\xEE\x85\x94"
#define ICON_LC_SHIELD               "\xEE\x85\x98"
#define ICON_LC_SHIELD_CHECK         "\xEE\x87\xBF"
#define ICON_LC_SQUARE               "\xEE\x85\xA7"
#define ICON_LC_STAR                 "\xEE\x85\xB6"
#define ICON_LC_TERMINAL             "\xEE\x86\x81"
#define ICON_LC_TOGGLE_LEFT          "\xEE\x86\x8B"
#define ICON_LC_TOGGLE_RIGHT         "\xEE\x86\x8C"
#define ICON_LC_TRASH                "\xEE\x86\x8E"
#define ICON_LC_UNLOCK               "\xEE\x84\x8C"
#define ICON_LC_USER                 "\xEE\x86\x9F"
#define ICON_LC_WIFI                 "\xEE\x86\xAE"
#define ICON_LC_X                    "\xEE\x86\xB2"
#define ICON_LC_ZAP                  "\xEE\x86\xB4"

#define ICON_LC_MIN 0xE038
#define ICON_LC_MAX 0xE529

static const unsigned short g_LucideIconRanges[] = {
    0xE038, 0xE529,
    0,
};
